# Generated by Django 4.1.2 on 2022-10-21 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usermodel",
            name="birth_day",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="usermodel",
            name="id_card",
            field=models.CharField(blank=True, max_length=9, null=True),
        ),
        migrations.AlterField(
            model_name="usermodel",
            name="user_image",
            field=models.ImageField(
                default="main/img/user_icon.png", upload_to="users/"
            ),
        ),
    ]
