# Generated by Django 4.1.2 on 2022-10-26 09:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AutherModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("age", models.PositiveIntegerField()),
                ("phone", models.CharField(max_length=13)),
            ],
            options={
                "verbose_name": "auther",
                "verbose_name_plural": "authers",
            },
        ),
        migrations.CreateModel(
            name="BookImageModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="books")),
            ],
        ),
        migrations.CreateModel(
            name="PublisherModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="TranslatorModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="FeaturesModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("isbn", models.CharField(max_length=50)),
                ("language", models.CharField(max_length=50)),
                ("write_type", models.CharField(max_length=50)),
                ("page_size", models.PositiveIntegerField()),
                ("cover", models.SmallIntegerField(choices=[("Hard", 1), ("Soft", 0)])),
                (
                    "paper_format",
                    models.SmallIntegerField(choices=[("A3", 1), ("A4", 2), ("A5", 3)]),
                ),
                ("publication_date", models.DateField()),
                (
                    "publisher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="books.publishermodel",
                    ),
                ),
                (
                    "translator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="books.translatormodel",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BookModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("price", models.FloatField()),
                ("discount", models.BooleanField(default=False)),
                ("status", models.BooleanField(default=True)),
                ("description", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "auther",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="books.authermodel",
                    ),
                ),
                (
                    "features",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="books.featuresmodel",
                    ),
                ),
                (
                    "image",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="books.bookimagemodel",
                    ),
                ),
            ],
            options={
                "verbose_name": "book",
                "verbose_name_plural": "books",
            },
        ),
    ]
