# Generated by Django 4.1.2 on 2022-10-26 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0002_bookmodel_real_price_alter_bookmodel_discount"),
    ]

    operations = [
        migrations.AlterField(
            model_name="featuresmodel",
            name="cover",
            field=models.SmallIntegerField(choices=[("1", "Hard"), ("0", "Soft")]),
        ),
        migrations.AlterField(
            model_name="featuresmodel",
            name="paper_format",
            field=models.SmallIntegerField(
                choices=[("1", "A3"), ("2", "A4"), ("3", "A5")]
            ),
        ),
    ]
